# Generated by Django 3.1.2 on 2020-11-04 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mensaje',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=50)),
                ('rut', models.CharField(max_length=50)),
                ('nombre', models.TextField()),
                ('telefono', models.CharField(max_length=50)),
                ('gato', models.TextField()),
            ],
        ),
    ]
